### PR TITLE
Clarify the installation instructions

### PR DESCRIPTION
**Pull request by sheevy**
Just in case someone gets puzzled by the problem described there: https://github.com/MilesCranmer/SymbolicRegression.jl/issues/1

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Thanks! This is a weird issue I'm seeing too. Let's try again once `SymbolicRegression.jl` is on the main Julia registry, maybe something about the git repo install or the Distributed import messes things up.

Cheers,
Miles

**Comment by patrick-kidger** [comment]
I think the usual pattern for this is something like this:

Install:
```julia
julia> import Pkg
julia> Pkg.activate(...)
julia> Pkg.add(url="https://github.com/MilesCranmer/SymbolicRegression.jl.git")
```
(Or the equivalent from `]`.)

Run:
```julia
import Distributed
Distributed.@everywhere begin
    import Pkg
    Pkg.activate(...)
    using SymbolicRegression
end

...
```

Or:
Run:
```julia
import Distributed

function foo()
    Distributed.@everywhere Main.eval(quote
        import Pkg
        Pkg.activate(...)
        using SymbolicRegression
    end)

    ...
end
```

**Comment by patrick-kidger** [comment]
(Although incidentally I think this Distributed business should be moved inside SymbolicRegression rather than requiring this from the user.)

**Comment by MilesCranmer** [comment]
Thanks @patrick-kidger!! This is very helpful! Will add this to the README.

Cheers,
Miles

**Pull request merged**
