### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by spaette**
dumped repo strings exposed a few typos

### CODE REVIEW

**Review by MilesCranmer — APPROVED** [review]

**Comment by spaette** [comment]
@MilesCranmer

the logo.svg file doesn't look correct

that being said if the `<tspan>` elements are removed

the text is shifted to the left from its current position

```
<text class="cls-18" transform="translate(49.61 320.26)">SymbolicReg<tspan class="cls-19" x="241.8" y="0">r</tspan><tspan x="255.85" y="0">ession.jl</tspan></text>
```

**Comment by MilesCranmer** [comment]
Hm, I'm not sure. THe docs are generated by https://github.com/MilesCranmer/SymbolicRegression.jl/blob/master/docs/make.jl

**Comment by spaette** [comment]
with `<tspan>` elements removed

logo

**Comment by MilesCranmer** [comment]
Oh, _within_ the svg you mean! That seems to be browser-dependent, it looks ok on my system. But yeah I'm happy to take a PR if you'd be so kind

**Comment by spaette** [comment]
Using Chromium and Firefox both the GitHub rendered .svg and the website rendering exhibit a gap in the text.

```
.cls-19{letter-spacing:-0.01em;}.cls-20{clip-path:url(#clip-path-6);}
```

cleanly editing the .svg

With the `<tspan>` elements removed `class="cls-19"` is thereby removed, which results in a gap in the class numbering as `class="cls-20"` appears as used later in the file. If the text in the right side of the previous comment's .png image not being horizontally centred (under the graphics) doesn't bother you it would be a simple pull to submit.

**Comment by MilesCranmer** [comment]
Sounds good, I'd be happy to take the PR!

**Comment by spaette** [comment]
I didn't know how to center the text.

**Comment by spaette** [comment]
Using Chrome on a mobile device the GitHub rendered .svg does not exhibit the gap in the text.

Of `#332`'s commit same browser/device has the text **Added** superimposed over the text W: 213px | H: 150px.

**Comment by spaette** [comment]
@MilesCranmer 

Any clue why the checks don't complete on my other pull?

**Pull request merged**
