### PR TITLE
tweak

### PR DESCRIPTION
**Pull request by spaette**
classes resequenced and `<tspan>` elements removed

### CODE REVIEW

**Comment by spaette** [comment]
@MilesCranmer 

The checks don't complete on this pull.

**Comment by spaette** [comment]
Doesn't appear to be an interest in this pull.

**Comment by MilesCranmer** [comment]
(Just haven't had time to verify the rendering; sorry. Please keep it open though)

**Comment by spaette** [comment]
`https://astroautomata.com/SymbolicRegression.jl/dev/`

FWIW, I opened the above in the Firefox browser and saved that webpage to example.html. That action created the file example.html and a sibling directory as example_files. I then substituted the mentioned directory's logo.svg for the same named file from my fork. Thereafter opening example.html in various browsers the substituted .svg rendered as expected (i.e. without the gap in the text).

**Comment by spaette** [comment]
It seems like it's been a while since this was opened.

**Pull request merged**
